-- Seed content for skill_items — a stroke-by-stroke NTRP skill checklist
-- (forehand/backhand shot types, net game, serve variety, movement),
-- described at every level band 1.0 through 7.0. Run after schema.sql.

insert into public.skill_items (pathway, level_min, level_max, group_label, category, title, sort_order, description) values
  ('ntrp', 1.0, 1.5, 'Forehand', 'forehand_high', 'Forehand — High Ball', 1, 'Contacts a fed shoulder-high ball with a continental-ish/eastern grip and pushes it forward over the net; consistency, not power, is the goal.'),
  ('ntrp', 2.0, 2.5, 'Forehand', 'forehand_high', 'Forehand — High Ball', 1, 'Adjusts the swing plane to meet a high-bouncing ball at chest-to-shoulder height with a compact backswing, keeping the ball in the court.'),
  ('ntrp', 3.0, 3.0, 'Forehand', 'forehand_high', 'Forehand — High Ball', 1, 'Drives a high forehand with a full swing and eastern/semi-western grip, directing it down the middle with medium pace.'),
  ('ntrp', 3.5, 3.5, 'Forehand', 'forehand_high', 'Forehand — High Ball', 1, 'Handles shoulder-high balls with a semi-western grip and a slightly steeper swing path, keeping depth and directional control.'),
  ('ntrp', 4.0, 4.0, 'Forehand', 'forehand_high', 'Forehand — High Ball', 1, 'Takes a high ball on the rise or at the peak with reliable depth and directional control on both cross-court and down-the-line targets.'),
  ('ntrp', 4.5, 4.5, 'Forehand', 'forehand_high', 'Forehand — High Ball', 1, 'Generates pace and heavy topspin on high balls, using the extra time to run around and attack with the inside-out forehand when useful.'),
  ('ntrp', 5.0, 5.0, 'Forehand', 'forehand_high', 'Forehand — High Ball', 1, 'Turns a high, attackable ball into a weapon — steps in, drives through the shot, and finishes points from this position.'),
  ('ntrp', 5.5, 6.0, 'Forehand', 'forehand_high', 'Forehand — High Ball', 1, 'Handles any height of incoming ball offensively, disguising a high forehand as either a heavy topspin rally shot or a flatter putaway.'),
  ('ntrp', 6.5, 7.0, 'Forehand', 'forehand_high', 'Forehand — High Ball', 1, 'Elite shot tolerance and disguise on high balls at match pace — a coach-refined, individualized skill at this tier.'),
  ('ntrp', 1.0, 1.5, 'Forehand', 'forehand_low', 'Forehand — Low Ball', 2, 'Bends the knees to get down to a low, short-hopped ball and lifts it back over the net with a simple, controlled swing.'),
  ('ntrp', 2.0, 2.5, 'Forehand', 'forehand_low', 'Forehand — Low Ball', 2, 'Gets the racquet head below the ball on a low bounce and lifts through contact with knees bent, aiming for the middle of the court.'),
  ('ntrp', 3.0, 3.0, 'Forehand', 'forehand_low', 'Forehand — Low Ball', 2, 'Adjusts stance and knee bend to drive a low ball with topspin, keeping the swing path low-to-high through contact.'),
  ('ntrp', 3.5, 3.5, 'Forehand', 'forehand_low', 'Forehand — Low Ball', 2, 'Controls depth and direction on a low forehand using a more compact backswing and solid knee bend, without overhitting.'),
  ('ntrp', 4.0, 4.0, 'Forehand', 'forehand_low', 'Forehand — Low Ball', 2, 'Handles low, skidding balls with balance and a controlled low-to-high path, keeping the shot deep or attacking a short low ball.'),
  ('ntrp', 4.5, 4.5, 'Forehand', 'forehand_low', 'Forehand — Low Ball', 2, 'Generates spin and pace on low balls with efficient footwork into the shot, staying balanced through a longer swing.'),
  ('ntrp', 5.0, 5.0, 'Forehand', 'forehand_low', 'Forehand — Low Ball', 2, 'Turns a low ball into an attacking opportunity when short, or a heavy, deep neutralizing shot when it''s not — reads the ball type instantly.'),
  ('ntrp', 5.5, 6.0, 'Forehand', 'forehand_low', 'Forehand — Low Ball', 2, 'Full shot tolerance on low balls under match pressure, with the footwork efficiency to redirect the ball to any target.'),
  ('ntrp', 6.5, 7.0, 'Forehand', 'forehand_low', 'Forehand — Low Ball', 2, 'Elite low-ball defense and offense, transitioning seamlessly between the two — a coach-refined, individualized skill at this tier.'),
  ('ntrp', 1.0, 1.5, 'Forehand', 'forehand_topspin', 'Forehand — Topspin', 3, 'Introduces a gentle low-to-high brushing motion on the forehand — more about the feel of the swing path than actual spin produced.'),
  ('ntrp', 2.0, 2.5, 'Forehand', 'forehand_topspin', 'Forehand — Topspin', 3, 'Develops a consistent low-to-high swing path on the forehand so the ball clears the net with margin.'),
  ('ntrp', 3.0, 3.0, 'Forehand', 'forehand_topspin', 'Forehand — Topspin', 3, 'Produces reliable topspin on the forehand with an eastern/semi-western grip, creating net clearance and depth.'),
  ('ntrp', 3.5, 3.5, 'Forehand', 'forehand_topspin', 'Forehand — Topspin', 3, 'Uses topspin as a shape tool — clearing the net by 3+ feet to buy time and control depth, not just for pace.'),
  ('ntrp', 4.0, 4.0, 'Forehand', 'forehand_topspin', 'Forehand — Topspin', 3, 'Combines topspin with depth and direction on both cross-court and down-the-line targets, varying spin amount by situation.'),
  ('ntrp', 4.5, 4.5, 'Forehand', 'forehand_topspin', 'Forehand — Topspin', 3, 'Adds heavy, high-clearing topspin as a tactical option to reset rallies and move opponents side to side.'),
  ('ntrp', 5.0, 5.0, 'Forehand', 'forehand_topspin', 'Forehand — Topspin', 3, 'Uses forehand topspin as a genuine weapon — heavy enough to push opponents behind the baseline and set up the next shot.'),
  ('ntrp', 5.5, 6.0, 'Forehand', 'forehand_topspin', 'Forehand — Topspin', 3, 'Full command of topspin variety (moderate to heavy) on demand, mid-rally, to control tempo against any opponent style.'),
  ('ntrp', 6.5, 7.0, 'Forehand', 'forehand_topspin', 'Forehand — Topspin', 3, 'Elite topspin variety and disguise at match pace — a coach-refined, individualized skill at this tier.'),
  ('ntrp', 1.0, 1.5, 'Forehand', 'forehand_slice', 'Forehand — Slice', 4, 'Not yet introduced — focus stays on basic forehand contact and consistency at this stage.'),
  ('ntrp', 2.0, 2.5, 'Forehand', 'forehand_slice', 'Forehand — Slice', 4, 'Introduces a simple flat-to-slightly-underspin forehand block for emergency defense on a fast ball.'),
  ('ntrp', 3.0, 3.0, 'Forehand', 'forehand_slice', 'Forehand — Slice', 4, 'Uses a basic forehand slice to block back a fast or awkward ball, prioritizing getting it back in play.'),
  ('ntrp', 3.5, 3.5, 'Forehand', 'forehand_slice', 'Forehand — Slice', 4, 'Develops a controlled forehand slice for defense and to change the rhythm of a rally, with a continental-ish grip.'),
  ('ntrp', 4.0, 4.0, 'Forehand', 'forehand_slice', 'Forehand — Slice', 4, 'Uses forehand slice purposefully to approach the net or to defend a wide, stretched ball with underspin control.'),
  ('ntrp', 4.5, 4.5, 'Forehand', 'forehand_slice', 'Forehand — Slice', 4, 'Varies forehand slice depth and pace as a tactical tool to disrupt an opponent''s rhythm or set up net approaches.'),
  ('ntrp', 5.0, 5.0, 'Forehand', 'forehand_slice', 'Forehand — Slice', 4, 'Deploys forehand slice as a genuine variety weapon — low, skidding, and disguised as a topspin shot until late.'),
  ('ntrp', 5.5, 6.0, 'Forehand', 'forehand_slice', 'Forehand — Slice', 4, 'Full tactical command of forehand slice — depth, low bounce, and disguise — integrated into complex point patterns.'),
  ('ntrp', 6.5, 7.0, 'Forehand', 'forehand_slice', 'Forehand — Slice', 4, 'Elite forehand slice variety and disguise — a coach-refined, individualized skill at this tier.'),
  ('ntrp', 1.0, 1.5, 'Forehand', 'forehand_dropshot', 'Forehand — Drop Shot', 5, 'Not yet introduced at this stage.'),
  ('ntrp', 2.0, 2.5, 'Forehand', 'forehand_dropshot', 'Forehand — Drop Shot', 5, 'Introduces the concept through fun, soft-touch mini-games rather than live-rally execution.'),
  ('ntrp', 3.0, 3.0, 'Forehand', 'forehand_dropshot', 'Forehand — Drop Shot', 5, 'Attempts a basic forehand drop shot off a short, slow feed, focusing on a soft touch over the net.'),
  ('ntrp', 3.5, 3.5, 'Forehand', 'forehand_dropshot', 'Forehand — Drop Shot', 5, 'Executes a forehand drop shot with disguise from a normal swing, aimed at a short ball opportunity.'),
  ('ntrp', 4.0, 4.0, 'Forehand', 'forehand_dropshot', 'Forehand — Drop Shot', 5, 'Reads a short ball and executes a forehand drop shot with good disguise and touch, following it in when appropriate.'),
  ('ntrp', 4.5, 4.5, 'Forehand', 'forehand_dropshot', 'Forehand — Drop Shot', 5, 'Uses the forehand drop shot as a real tactical weapon against opponents who camp on the baseline, with backspin control.'),
  ('ntrp', 5.0, 5.0, 'Forehand', 'forehand_dropshot', 'Forehand — Drop Shot', 5, 'Combines forehand drop shot with a lob follow-up threat, forcing opponents into a genuine dilemma.'),
  ('ntrp', 5.5, 6.0, 'Forehand', 'forehand_dropshot', 'Forehand — Drop Shot', 5, 'Full tactical integration of the forehand drop shot into point patterns at match speed and pressure.'),
  ('ntrp', 6.5, 7.0, 'Forehand', 'forehand_dropshot', 'Forehand — Drop Shot', 5, 'Elite touch and disguise on the forehand drop shot — a coach-refined, individualized skill at this tier.'),
  ('ntrp', 1.0, 1.5, 'Backhand', 'backhand_high', 'Backhand — High Ball', 6, 'Uses two hands to push a fed, shoulder-high ball back over the net with a simple, short swing.'),
  ('ntrp', 2.0, 2.5, 'Backhand', 'backhand_high', 'Backhand — High Ball', 6, 'Adjusts the two-handed grip and stance to meet a high-bouncing ball at chest height, focusing on contact consistency.'),
  ('ntrp', 3.0, 3.0, 'Backhand', 'backhand_high', 'Backhand — High Ball', 6, 'Drives a high two-handed backhand down the middle with medium pace, using both hands through the full swing.'),
  ('ntrp', 3.5, 3.5, 'Backhand', 'backhand_high', 'Backhand — High Ball', 6, 'Handles shoulder-high balls on the backhand with directional control, though this wing typically lags the forehand in reliability at this level.'),
  ('ntrp', 4.0, 4.0, 'Backhand', 'backhand_high', 'Backhand — High Ball', 6, 'Takes a high backhand with reliable depth and directional control, matching the forehand''s dependability.'),
  ('ntrp', 4.5, 4.5, 'Backhand', 'backhand_high', 'Backhand — High Ball', 6, 'Generates pace and topspin on a high two-handed backhand, using the extra time to attack when the ball sits up.'),
  ('ntrp', 5.0, 5.0, 'Backhand', 'backhand_high', 'Backhand — High Ball', 6, 'Turns a high, attackable backhand into a weapon shot, driving through with confidence.'),
  ('ntrp', 5.5, 6.0, 'Backhand', 'backhand_high', 'Backhand — High Ball', 6, 'Handles any height of incoming ball on the backhand offensively, matching the forehand''s shot tolerance.'),
  ('ntrp', 6.5, 7.0, 'Backhand', 'backhand_high', 'Backhand — High Ball', 6, 'Elite shot tolerance and disguise on high backhands at match pace — a coach-refined, individualized skill at this tier.'),
  ('ntrp', 1.0, 1.5, 'Backhand', 'backhand_low', 'Backhand — Low Ball', 7, 'Bends the knees to get down to a low ball on the backhand side and lifts it back with two hands.'),
  ('ntrp', 2.0, 2.5, 'Backhand', 'backhand_low', 'Backhand — Low Ball', 7, 'Gets the racquet below a low ball on the backhand side and lifts through contact with knees bent.'),
  ('ntrp', 3.0, 3.0, 'Backhand', 'backhand_low', 'Backhand — Low Ball', 7, 'Adjusts stance and knee bend to drive a low two-handed backhand with topspin.'),
  ('ntrp', 3.5, 3.5, 'Backhand', 'backhand_low', 'Backhand — Low Ball', 7, 'Controls depth and direction on a low backhand using solid knee bend and a compact backswing.'),
  ('ntrp', 4.0, 4.0, 'Backhand', 'backhand_low', 'Backhand — Low Ball', 7, 'Handles low, skidding balls on the backhand with balance, keeping the shot deep or attacking a short one.'),
  ('ntrp', 4.5, 4.5, 'Backhand', 'backhand_low', 'Backhand — Low Ball', 7, 'Generates spin and pace on low backhands with efficient footwork into the shot.'),
  ('ntrp', 5.0, 5.0, 'Backhand', 'backhand_low', 'Backhand — Low Ball', 7, 'Turns a low backhand into an attacking opportunity when short, or a heavy defensive shot when deep.'),
  ('ntrp', 5.5, 6.0, 'Backhand', 'backhand_low', 'Backhand — Low Ball', 7, 'Full shot tolerance on low backhands under match pressure, redirecting to any target.'),
  ('ntrp', 6.5, 7.0, 'Backhand', 'backhand_low', 'Backhand — Low Ball', 7, 'Elite low-ball backhand defense and offense — a coach-refined, individualized skill at this tier.'),
  ('ntrp', 1.0, 1.5, 'Backhand', 'backhand_topspin', 'Backhand — Topspin', 8, 'Introduces a gentle low-to-high two-handed swing path, focused on feel over actual spin.'),
  ('ntrp', 2.0, 2.5, 'Backhand', 'backhand_topspin', 'Backhand — Topspin', 8, 'Develops a consistent low-to-high two-handed swing path for net clearance and margin.'),
  ('ntrp', 3.0, 3.0, 'Backhand', 'backhand_topspin', 'Backhand — Topspin', 8, 'Produces reliable topspin on the two-handed backhand with a full, connected swing.'),
  ('ntrp', 3.5, 3.5, 'Backhand', 'backhand_topspin', 'Backhand — Topspin', 8, 'Uses backhand topspin for shape and net clearance — typically still less developed than the forehand at this level.'),
  ('ntrp', 4.0, 4.0, 'Backhand', 'backhand_topspin', 'Backhand — Topspin', 8, 'Combines backhand topspin with depth and direction on both cross-court and down-the-line targets.'),
  ('ntrp', 4.5, 4.5, 'Backhand', 'backhand_topspin', 'Backhand — Topspin', 8, 'Adds heavy, high-clearing backhand topspin as a tactical reset and pace-control tool.'),
  ('ntrp', 5.0, 5.0, 'Backhand', 'backhand_topspin', 'Backhand — Topspin', 8, 'Uses backhand topspin as a genuine weapon, matching the forehand''s ability to push opponents back.'),
  ('ntrp', 5.5, 6.0, 'Backhand', 'backhand_topspin', 'Backhand — Topspin', 8, 'Full command of backhand topspin variety on demand, mid-rally, matching the forehand wing.'),
  ('ntrp', 6.5, 7.0, 'Backhand', 'backhand_topspin', 'Backhand — Topspin', 8, 'Elite backhand topspin variety and disguise — a coach-refined, individualized skill at this tier.'),
  ('ntrp', 1.0, 1.5, 'Backhand', 'backhand_slice', 'Backhand — Slice', 9, 'Not yet introduced at this stage.'),
  ('ntrp', 2.0, 2.5, 'Backhand', 'backhand_slice', 'Backhand — Slice', 9, 'Introduces a one-handed slice block on the backhand for a simple, controlled way to return a fast ball.'),
  ('ntrp', 3.0, 3.0, 'Backhand', 'backhand_slice', 'Backhand — Slice', 9, 'Uses a basic one-handed backhand slice for defense, prioritizing getting the ball back in play.'),
  ('ntrp', 3.5, 3.5, 'Backhand', 'backhand_slice', 'Backhand — Slice', 9, 'Develops a controlled one-handed backhand slice for defense and rhythm changes — a core 3.5-level skill.'),
  ('ntrp', 4.0, 4.0, 'Backhand', 'backhand_slice', 'Backhand — Slice', 9, 'Uses backhand slice purposefully to approach the net or defend a stretched wide ball with control.'),
  ('ntrp', 4.5, 4.5, 'Backhand', 'backhand_slice', 'Backhand — Slice', 9, 'Varies backhand slice depth and pace tactically to disrupt rhythm or set up net approaches.'),
  ('ntrp', 5.0, 5.0, 'Backhand', 'backhand_slice', 'Backhand — Slice', 9, 'Deploys backhand slice as a real variety weapon — low, skidding, and disguised.'),
  ('ntrp', 5.5, 6.0, 'Backhand', 'backhand_slice', 'Backhand — Slice', 9, 'Full tactical command of backhand slice integrated into complex point patterns.'),
  ('ntrp', 6.5, 7.0, 'Backhand', 'backhand_slice', 'Backhand — Slice', 9, 'Elite backhand slice variety and disguise — a coach-refined, individualized skill at this tier.'),
  ('ntrp', 1.0, 1.5, 'Backhand', 'backhand_dropshot', 'Backhand — Drop Shot', 10, 'Not yet introduced at this stage.'),
  ('ntrp', 2.0, 2.5, 'Backhand', 'backhand_dropshot', 'Backhand — Drop Shot', 10, 'Introduces the concept through fun, soft-touch mini-games.'),
  ('ntrp', 3.0, 3.0, 'Backhand', 'backhand_dropshot', 'Backhand — Drop Shot', 10, 'Attempts a basic backhand drop shot off a short, slow feed with a soft touch.'),
  ('ntrp', 3.5, 3.5, 'Backhand', 'backhand_dropshot', 'Backhand — Drop Shot', 10, 'Executes a backhand drop shot with disguise from the slice motion, aimed at a short-ball opportunity.'),
  ('ntrp', 4.0, 4.0, 'Backhand', 'backhand_dropshot', 'Backhand — Drop Shot', 10, 'Reads a short ball and executes a backhand drop shot with good disguise, following it in when appropriate.'),
  ('ntrp', 4.5, 4.5, 'Backhand', 'backhand_dropshot', 'Backhand — Drop Shot', 10, 'Uses the backhand drop shot as a tactical weapon against baseline-camping opponents.'),
  ('ntrp', 5.0, 5.0, 'Backhand', 'backhand_dropshot', 'Backhand — Drop Shot', 10, 'Combines backhand drop shot with a lob follow-up threat for a genuine tactical dilemma.'),
  ('ntrp', 5.5, 6.0, 'Backhand', 'backhand_dropshot', 'Backhand — Drop Shot', 10, 'Full tactical integration of the backhand drop shot into point patterns at match pressure.'),
  ('ntrp', 6.5, 7.0, 'Backhand', 'backhand_dropshot', 'Backhand — Drop Shot', 10, 'Elite touch and disguise on the backhand drop shot — a coach-refined, individualized skill at this tier.'),
  ('ntrp', 1.0, 1.5, 'Net Game', 'overhead', 'Overhead / Smash', 11, 'Practices a basic overhead swing on a stationary, low-tossed ball, more like a serve motion than a live smash.'),
  ('ntrp', 2.0, 2.5, 'Net Game', 'overhead', 'Overhead / Smash', 11, 'Tracks a lobbed ball and attempts an overhead with a simple, serve-like motion, focused on contact.'),
  ('ntrp', 3.0, 3.0, 'Net Game', 'overhead', 'Overhead / Smash', 11, 'Executes an overhead on a moderately lobbed ball with a full service-style motion and reasonable court positioning.'),
  ('ntrp', 3.5, 3.5, 'Net Game', 'overhead', 'Overhead / Smash', 11, 'Handles a lobbed ball with a reliable overhead, tracking it back with proper footwork before finishing the point.'),
  ('ntrp', 4.0, 4.0, 'Net Game', 'overhead', 'Overhead / Smash', 11, 'Finishes points reliably with the overhead off a lob, using proper spacing and footwork to track the ball back.'),
  ('ntrp', 4.5, 4.5, 'Net Game', 'overhead', 'Overhead / Smash', 11, 'Handles deep, high lobs with a reliable overhead, including the bounce-overhead when needed.'),
  ('ntrp', 5.0, 5.0, 'Net Game', 'overhead', 'Overhead / Smash', 11, 'Uses the overhead as a confident weapon, closing out points aggressively off any lob.'),
  ('ntrp', 5.5, 6.0, 'Net Game', 'overhead', 'Overhead / Smash', 11, 'Full command of the overhead including in-air, bounce, and angled putaways under match pressure.'),
  ('ntrp', 6.5, 7.0, 'Net Game', 'overhead', 'Overhead / Smash', 11, 'Elite overhead reliability and placement — a coach-refined, individualized skill at this tier.'),
  ('ntrp', 1.0, 1.5, 'Net Game', 'volley_forehand', 'Volley — Forehand', 12, 'Practices a basic forehand volley block off a gentle, close-range feed, focusing on racquet-face control.'),
  ('ntrp', 2.0, 2.5, 'Net Game', 'volley_forehand', 'Volley — Forehand', 12, 'Blocks a forehand volley with a short, controlled motion from a closer net position.'),
  ('ntrp', 3.0, 3.0, 'Net Game', 'volley_forehand', 'Volley — Forehand', 12, 'Executes a forehand volley with a short punch motion and continental-ish grip from mid-court or net.'),
  ('ntrp', 3.5, 3.5, 'Net Game', 'volley_forehand', 'Volley — Forehand', 12, 'Uses a compact forehand volley with directional control on balls within reach, still developing depth and touch.'),
  ('ntrp', 4.0, 4.0, 'Net Game', 'volley_forehand', 'Volley — Forehand', 12, 'Directs forehand volleys with depth and placement most of the time, including a basic touch/drop volley.'),
  ('ntrp', 4.5, 4.5, 'Net Game', 'volley_forehand', 'Volley — Forehand', 12, 'Adds power and angle variety to the forehand volley, closing out points from a variety of net positions.'),
  ('ntrp', 5.0, 5.0, 'Net Game', 'volley_forehand', 'Volley — Forehand', 12, 'Uses the forehand volley as a reliable finishing shot with full touch and power range.'),
  ('ntrp', 5.5, 6.0, 'Net Game', 'volley_forehand', 'Volley — Forehand', 12, 'Full forehand volley command — reflex volleys, touch volleys, and put-aways — under match pressure.'),
  ('ntrp', 6.5, 7.0, 'Net Game', 'volley_forehand', 'Volley — Forehand', 12, 'Elite forehand volley reliability and touch — a coach-refined, individualized skill at this tier.'),
  ('ntrp', 1.0, 1.5, 'Net Game', 'volley_backhand', 'Volley — Backhand', 13, 'Practices a basic backhand volley block off a gentle, close-range feed.'),
  ('ntrp', 2.0, 2.5, 'Net Game', 'volley_backhand', 'Volley — Backhand', 13, 'Blocks a backhand volley with a short, controlled motion from a closer net position.'),
  ('ntrp', 3.0, 3.0, 'Net Game', 'volley_backhand', 'Volley — Backhand', 13, 'Executes a backhand volley with a short punch motion and continental grip from mid-court or net.'),
  ('ntrp', 3.5, 3.5, 'Net Game', 'volley_backhand', 'Volley — Backhand', 13, 'Uses a compact backhand volley with directional control on balls within reach.'),
  ('ntrp', 4.0, 4.0, 'Net Game', 'volley_backhand', 'Volley — Backhand', 13, 'Directs backhand volleys with depth and placement most of the time, including a basic touch/drop volley.'),
  ('ntrp', 4.5, 4.5, 'Net Game', 'volley_backhand', 'Volley — Backhand', 13, 'Adds power and angle variety to the backhand volley, closing out points from a variety of net positions.'),
  ('ntrp', 5.0, 5.0, 'Net Game', 'volley_backhand', 'Volley — Backhand', 13, 'Uses the backhand volley as a reliable finishing shot with full touch and power range.'),
  ('ntrp', 5.5, 6.0, 'Net Game', 'volley_backhand', 'Volley — Backhand', 13, 'Full backhand volley command — reflex volleys, touch volleys, and put-aways — under match pressure.'),
  ('ntrp', 6.5, 7.0, 'Net Game', 'volley_backhand', 'Volley — Backhand', 13, 'Elite backhand volley reliability and touch — a coach-refined, individualized skill at this tier.'),
  ('ntrp', 1.0, 1.5, 'Serve', 'serve_flat', 'Serve — Flat', 14, 'Practices a basic underhand or simple overhand toss-and-hit motion aimed at getting the ball into the box.'),
  ('ntrp', 2.0, 2.5, 'Serve', 'serve_flat', 'Serve — Flat', 14, 'Develops a full overhand service motion, aiming to land flat serves in the box consistently.'),
  ('ntrp', 3.0, 3.0, 'Serve', 'serve_flat', 'Serve — Flat', 14, 'Serves with a reasonably consistent flat/first-serve motion, targeting the box more than precise placement.'),
  ('ntrp', 3.5, 3.5, 'Serve', 'serve_flat', 'Serve — Flat', 14, 'Places a flat first serve to general target zones (T, body, wide) with reasonable, though not fully reliable, consistency.'),
  ('ntrp', 4.0, 4.0, 'Serve', 'serve_flat', 'Serve — Flat', 14, 'Serves flat with reliable placement to all three zones most of the time, generating some pace.'),
  ('ntrp', 4.5, 4.5, 'Serve', 'serve_flat', 'Serve — Flat', 14, 'Uses the flat serve as a power option, hit with real pace and placed to set up the next shot.'),
  ('ntrp', 5.0, 5.0, 'Serve', 'serve_flat', 'Serve — Flat', 14, 'Uses flat serve pace and placement as a weapon to earn free points or weak returns.'),
  ('ntrp', 5.5, 6.0, 'Serve', 'serve_flat', 'Serve — Flat', 14, 'Full command of flat serve pace and placement under match pressure, sequenced with other serve types.'),
  ('ntrp', 6.5, 7.0, 'Serve', 'serve_flat', 'Serve — Flat', 14, 'Elite flat serve pace, placement, and disguise — a coach-refined, individualized skill at this tier.'),
  ('ntrp', 1.0, 1.5, 'Serve', 'serve_slice', 'Serve — Slice', 15, 'Not yet introduced — focus stays on a basic flat toss-and-hit motion.'),
  ('ntrp', 2.0, 2.5, 'Serve', 'serve_slice', 'Serve — Slice', 15, 'Not yet introduced — focus stays on landing a consistent flat serve in the box.'),
  ('ntrp', 3.0, 3.0, 'Serve', 'serve_slice', 'Serve — Slice', 15, 'Introduces a basic side-spin slice serve concept, mostly through toss and grip awareness drills.'),
  ('ntrp', 3.5, 3.5, 'Serve', 'serve_slice', 'Serve — Slice', 15, 'Attempts a slice serve with a continental grip and side-spin toss, primarily out wide, with developing reliability.'),
  ('ntrp', 4.0, 4.0, 'Serve', 'serve_slice', 'Serve — Slice', 15, 'Uses a slice serve to pull the returner off the court, especially out wide in the deuce court.'),
  ('ntrp', 4.5, 4.5, 'Serve', 'serve_slice', 'Serve — Slice', 15, 'Reliably places the slice serve to multiple zones, disguising the toss to match the flat/kick serve.'),
  ('ntrp', 5.0, 5.0, 'Serve', 'serve_slice', 'Serve — Slice', 15, 'Uses slice serve placement and disguise as a real weapon to open up the court for the next shot.'),
  ('ntrp', 5.5, 6.0, 'Serve', 'serve_slice', 'Serve — Slice', 15, 'Full command of slice serve variety and disguise, sequenced tactically within a service game.'),
  ('ntrp', 6.5, 7.0, 'Serve', 'serve_slice', 'Serve — Slice', 15, 'Elite slice serve disguise and placement — a coach-refined, individualized skill at this tier.'),
  ('ntrp', 1.0, 1.5, 'Serve', 'serve_kick', 'Serve — Kick', 16, 'Not yet introduced at this stage.'),
  ('ntrp', 2.0, 2.5, 'Serve', 'serve_kick', 'Serve — Kick', 16, 'Not yet introduced at this stage.'),
  ('ntrp', 3.0, 3.0, 'Serve', 'serve_kick', 'Serve — Kick', 16, 'Not yet introduced — focus stays on flat serve consistency and slice-serve toss awareness.'),
  ('ntrp', 3.5, 3.5, 'Serve', 'serve_kick', 'Serve — Kick', 16, 'Introduces the kick serve concept and toss position, primarily as a reliable, safer second serve.'),
  ('ntrp', 4.0, 4.0, 'Serve', 'serve_kick', 'Serve — Kick', 16, 'Uses a developing kick serve as a second-serve option, reducing double faults under pressure.'),
  ('ntrp', 4.5, 4.5, 'Serve', 'serve_kick', 'Serve — Kick', 16, 'Hits a reliable kick serve with real topspin bounce, disguised to look like the flat/slice toss.'),
  ('ntrp', 5.0, 5.0, 'Serve', 'serve_kick', 'Serve — Kick', 16, 'Uses the kick serve as a genuine second-serve weapon, with enough bounce to neutralize aggressive returners.'),
  ('ntrp', 5.5, 6.0, 'Serve', 'serve_kick', 'Serve — Kick', 16, 'Full command of kick serve depth, bounce, and disguise, integrated into service patterns.'),
  ('ntrp', 6.5, 7.0, 'Serve', 'serve_kick', 'Serve — Kick', 16, 'Elite kick serve bounce, disguise, and placement — a coach-refined, individualized skill at this tier.'),
  ('ntrp', 1.0, 1.5, 'Movement', 'footwork', 'Footwork / Movement', 17, 'Practices basic ready position, split-step timing, and simple side-to-side shuffling.'),
  ('ntrp', 2.0, 2.5, 'Movement', 'footwork', 'Footwork / Movement', 17, 'Develops consistent split-step timing and basic recovery to the middle after each shot.'),
  ('ntrp', 3.0, 3.0, 'Movement', 'footwork', 'Footwork / Movement', 17, 'Uses split-step and shuffle footwork to reach balls within a moderate range and recover to center.'),
  ('ntrp', 3.5, 3.5, 'Movement', 'footwork', 'Footwork / Movement', 17, 'Combines adjustment steps, recovery steps, and lateral movement to sustain longer rallies.'),
  ('ntrp', 4.0, 4.0, 'Movement', 'footwork', 'Footwork / Movement', 17, 'Uses efficient multi-directional footwork (forward, lateral, back) to construct and finish points.'),
  ('ntrp', 4.5, 4.5, 'Movement', 'footwork', 'Footwork / Movement', 17, 'Moves with efficient, economical footwork to handle pace and cover the full court under pressure.'),
  ('ntrp', 5.0, 5.0, 'Movement', 'footwork', 'Footwork / Movement', 17, 'Anticipates and moves early based on opponent cues, arriving balanced and ready to attack or defend.'),
  ('ntrp', 5.5, 6.0, 'Movement', 'footwork', 'Footwork / Movement', 17, 'Full match-speed movement efficiency, covering the court with minimal wasted steps under fatigue.'),
  ('ntrp', 6.5, 7.0, 'Movement', 'footwork', 'Footwork / Movement', 17, 'Elite court coverage and movement efficiency — a coach-refined, individualized skill at this tier.'),
  ('ntrp', 1.0, 1.5, 'Movement', 'warmup', 'Warm-Up Routine', 18, 'Follows a simple, coach-led warm-up of light movement and easy ball-tracking games before each session.'),
  ('ntrp', 2.0, 2.5, 'Movement', 'warmup', 'Warm-Up Routine', 18, 'Follows a short, structured warm-up (movement, easy rally) before each session with coach guidance.'),
  ('ntrp', 3.0, 3.0, 'Movement', 'warmup', 'Warm-Up Routine', 18, 'Runs through a basic self-led warm-up sequence (movement, groundstrokes) before drilling begins.'),
  ('ntrp', 3.5, 3.5, 'Movement', 'warmup', 'Warm-Up Routine', 18, 'Uses a structured warm-up sequence (groundstrokes, volleys, serves) before every session or match.'),
  ('ntrp', 4.0, 4.0, 'Movement', 'warmup', 'Warm-Up Routine', 18, 'Runs an efficient, complete warm-up (groundstrokes, volleys, overheads, serves, returns) before matches.'),
  ('ntrp', 4.5, 4.5, 'Movement', 'warmup', 'Warm-Up Routine', 18, 'Uses a focused, purposeful warm-up to prime specific patterns expected to matter that match.'),
  ('ntrp', 5.0, 5.0, 'Movement', 'warmup', 'Warm-Up Routine', 18, 'Runs a complete competitive warm-up with the same routine every time, home or away.'),
  ('ntrp', 5.5, 6.0, 'Movement', 'warmup', 'Warm-Up Routine', 18, 'Uses a tournament-caliber warm-up routine, adaptable to short warm-up windows under match conditions.'),
  ('ntrp', 6.5, 7.0, 'Movement', 'warmup', 'Warm-Up Routine', 18, 'Elite, individualized warm-up and activation routine — a coach-refined skill at this tier.');
